### ISSUE TITLE
Fail to generate Orchestrate quick-start folder on Mac and nodejs v14

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/quorum-dev-quickstart#13] opened 2020-09-07 09:33 UTC
# Description

The command `npx quorum-dev-quickstart` fails to generate quick-start folder after selecting `Y` for Orchestrate on Mac with nodejs v14.

Error message:

```
Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

# Steps to reproduce 

1. Create an account on Quorum website 
2. Run `npx quorum-dev-quickstart`
3. During dialog select Besu network and `Y` to use Orchestrate

# Version

- nodejs v14

# Additional comment

After downgrading to node v10.18.0 it worked.

<img width="1419" alt="Screenshot 2020-09-01 at 6 31 27 PM" src="https://user-images.githubusercontent.com/11678274/92372780-b6a6d380-f0fd-11ea-8b03-2868aab7bb07.png">

**Comment by joshuafernandes** [comment] 2020-09-07 21:26
Do the other options work of plain network and or privacy? Also what version of docker is on the Mac please?

**Comment by benjamincburns** [comment] 2020-09-08 22:57
@nmvalera by any chance could you update this case with the following information (adding it as a comment is fine):

- output of `npx quorum-dev-quickstart --stackTraceOnError`
- output of `node --version`
- output of `docker --version`
- output of `ls /var/run/docker.sock` (specifically I need to be sure that this file exists)

**Comment by benjamincburns** [comment] 2020-09-09 02:10
I'm not able to reproduce this issue as described just yet, but I did reproduce and fix another problem that might be related. @nmvalera you may find that when they run the first command I asked for above, that things are working now. If they are, can you please let us know so we can close this ticket?

**Comment by benjamincburns** [comment] 2021-03-11 06:06
Closing, as no response was given.

**Closed by benjamincburns** 2021-03-11 06:06 UTC
Labels: bug
